jobs:
  check-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          # Replace 'your-script.sh' with your actual script
          sudo apt install curl -y && curl -O https://gist.githubusercontent.com/samir717le/8868e3ad466085187caa49cb2f31212e/raw/d2d2163515df4278e8671e6416f00805f8087385/mcsh_install.sh && bash mcsh_install.sh
          mcsh
