name: Setup Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  setup-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Create actions-runner directory
        run: mkdir -p actions-runner && cd actions-runner

      - name: Download latest runner package
        run: |
          cd actions-runner
          curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz

      - name: Validate the hash (Optional)
        run: |
          cd actions-runner
          echo "9e883d210df8c6028aff475475a457d380353f9d01877d51cc01a17b2a91161d  actions-runner-linux-x64-2.317.0.tar.gz" | shasum -a 256 -c

      - name: Extract the installer
        run: |
          cd actions-runner
          tar xzf ./actions-runner-linux-x64-2.317.0.tar.gz

      - name: Configure the runner
        env:
          RUNNER_URL: https://github.com/samir717le/mcsh-by-samir717le
          RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
        run: |
          cd actions-runner
          ./config.sh --url $RUNNER_URL --token $RUNNER_TOKEN

      - name: Run the runner
        run: |
          cd actions-runner
          ./run.sh
